# Generated by Django 3.0.3 on 2020-02-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='autor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
