# Generated by Django 3.0.3 on 2020-02-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postagem_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='postagem',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
