# Generated by Django 3.0.3 on 2020-02-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200227_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
