# Generated by Django 3.0.3 on 2020-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_postagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
