# Generated by Django 3.0.3 on 2020-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200421_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.ImageField(blank=True, upload_to='media/pictures'),
        ),
    ]
