# Generated by Django 3.0.3 on 2020-06-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200628_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postagem',
        ),
    ]
